spring.application.name=gestionproductos

spring.mongodb.uri=mongodb+srv://leoodato_db_user:QVl9QjLJXKn9yN1u@backendjava.v1ok9uk.mongodb.net/?appName=BackendJava

spring.mongodb.database=gestionProductos